// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class BuyInsuranceTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    if(SetUp.Platform == 0) {
      System.setProperty("webdriver.chrome.driver", SetUp.chrome);
      driver = new ChromeDriver();
    }else{
      System.setProperty("webdriver.gecko.driver", SetUp.firefox);
      driver = new FirefoxDriver();
    }
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void buyInsurance() {
    driver.get("https://www.gmx.net/");
    driver.manage().window().setSize(new Dimension(1552, 840));

    driver.switchTo().frame(0);
    driver.switchTo().frame(0);

    {
      WebDriverWait wait = new WebDriverWait(driver, 10);
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//button[@id=\'save-all-conditionally\']")));
    }
    driver.findElement(By.xpath("//button[@id=\'save-all-conditionally\']")).click();

    driver.switchTo().defaultContent();
    driver.switchTo().defaultContent();

    {
      WebDriverWait wait = new WebDriverWait(driver, 10);
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//div[2]/div/label")));
    }
    driver.findElement(By.xpath("//div[2]/div/label")).click();
    vars.put("window_handles", driver.getWindowHandles());

    {
      WebDriverWait wait = new WebDriverWait(driver, 10);
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//nav/ul/li[9]/a/p")));
    }
    driver.findElement(By.xpath("//nav/ul/li[9]/a/p")).click();

    vars.put("win8738", waitForWindow(2000));
    vars.put("root", driver.getWindowHandle());
    driver.switchTo().window(vars.get("win8738").toString());
    driver.findElement(By.xpath("//a[contains(.,\'Beitrag berechnen\')]")).click();
    js.executeScript("window.scrollTo(0,100)");
    driver.findElement(By.xpath("//input[@id=\'bDay\']")).click();
    driver.findElement(By.xpath("//input[@id=\'bDay\']")).sendKeys("11");
    driver.findElement(By.xpath("//input[@id=\'bMonth\']")).click();
    driver.findElement(By.xpath("//input[@id=\'bMonth\']")).sendKeys("11");
    driver.findElement(By.xpath("//input[@id=\'bYear\']")).click();
    driver.findElement(By.xpath("//input[@id=\'bYear\']")).sendKeys("2000");
    driver.findElement(By.xpath("//button[@type=\'submit\']")).click();
    js.executeScript("window.scrollTo(0,400)");
    driver.findElement(By.xpath("//body[@id=\'top\']/div/div[3]/div/div[2]/div/div[2]/p[2]/a")).click();
    driver.findElement(By.xpath("//a[@id=\'cta-submit\']")).click();
  }
}
