// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ShareNewsTwtterTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    if(SetUp.Platform == 0) {
      System.setProperty("webdriver.chrome.driver", SetUp.chrome);
      driver = new ChromeDriver();
    }else{
      System.setProperty("webdriver.gecko.driver", SetUp.firefox);
      driver = new FirefoxDriver();
    }
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void shareNewsTwtter() throws InterruptedException {
    driver.get("https://www.gmx.net/");
    driver.manage().window().setSize(new Dimension(1552, 840));

    driver.switchTo().frame(0);
    driver.switchTo().frame(0);

    {
      WebDriverWait wait = new WebDriverWait(driver, 10);
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//button[@id=\'save-all-conditionally\']")));
    }
    driver.findElement(By.xpath("//button[@id=\'save-all-conditionally\']")).click();

    driver.switchTo().defaultContent();
    driver.switchTo().defaultContent();

    {
      WebDriverWait wait = new WebDriverWait(driver, 10);
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//div[@id=\'app\']/div/div/div[2]/section[2]/div/div[2]/div/a/figure/img")));
    }
    driver.findElement(By.xpath("//div[@id=\'app\']/div/div/div[2]/section[2]/div/div[2]/div/a/figure/img")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.xpath("//div[2]/span")).click();
    vars.put("win9542", waitForWindow(2000));
    vars.put("root", driver.getWindowHandle());
    driver.switchTo().window(vars.get("win9542").toString());
    driver.findElement(By.name("session[username_or_email]")).click();
    driver.findElement(By.name("session[username_or_email]")).sendKeys("PU6AEUv2oxxlvEs");
    driver.findElement(By.name("session[password]")).click();
    driver.findElement(By.name("session[password]")).sendKeys("abc12345678");
    driver.findElement(By.xpath("//div[@id=\'layers\']/div[2]/div/div/div/div/div/div[2]/div[2]/div/div[2]/div[2]/div/span/span/span")).click();
    driver.findElement(By.xpath("//div[@id=\'react-root\']/div/div/div[2]/main/div/div/div[2]/div/div/div/div[3]/div/div/span/span")).click();
    Thread.sleep(10000);
  }
}
